---
- name: Disable swap (if configured).
  command: swapoff -a
  when: ansible_memory_mb['swap']['total'] > 0
  tags: ['skip_ansible_lint']

- name: Ensure swap file doesn't exist (if configured).
  file:
    path: "{{ swap_file_path }}"
    state: absent

- name: Check if zram swap service exists
  command:
    systemctl list-units --all --type=service --no-legend 'swap-create@zram*'
  register: zram_service_check
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Disable zram swap using systemd
  systemd:
    name: "{{ zram_service_check.stdout.split()[0] }}"
    state: stopped
    enabled: false
  when:
    - ansible_os_family == "RedHat"
    - zram_service_check.stdout != ""

- name: Remove zram-generator-defaults
  package:
    name: zram-generator-defaults
    state: absent
  when: ansible_os_family == "RedHat"
