---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Enable swap
      include_role:
        name: geerlingguy.swap
      vars:
        swap_file_size_mb: '256'
        swap_test_mode: true

    # - name: Disable swap
    #   include_role:
    #     name: geerlingguy.swap
    #   vars:
    #     swap_file_state: absent
